name: btc-jupyter
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13.2
  - matplotlib
  - mplfinance
  - numpy
  - pandas
  - ta
  - ipykernel
  - jupyterlab
  - tabulate

